<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if ($this->isAmazonPayButtonEnabled()): ?>

  <div id="<?php echo $this->getAmazonPayButtonId(); ?>"></div>

  <script type="text/javascript">
    var authRequest;

    var AmazonButtonOptions = {
        type: "PwA",
        authorization: function() {
            loginOptions = {
                scope: "profile payments:widget payments:shipping_address<?php print $this->getAdditionalScope(); ?>",
                response_type: 'token',
                popup: <?php print $this->isPopup(); ?>
            };

            authRequest = amazon.Login.authorize (loginOptions, "<?php echo (!$this->isPopup()) ? $this->getLoginAuthUrl() : $this->getCheckoutUrl(); ?>");
        },
        onError: function(error) {
            console.log(error);
        }
    };

    OffAmazonPayments.Button("<?php echo $this->getAmazonPayButtonId(); ?>", "<?php echo $this->getSellerId(); ?>", AmazonButtonOptions);

  </script>

<?php endif; ?>