<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if ($this->isAmazonPayButtonEnabled()): ?>

  <div id="<?php echo $this->getAmazonPayButtonId(); ?>"></div>

  <script type="text/javascript">
    var authRequest;

    var AmazonButtonOptions = {
        type: "PwA",
        authorization: function() {
            loginOptions = {
                scope: "profile payments:widget payments:shipping_address"
            };

            authRequest = amazon.Login.authorize (loginOptions, "<?php echo $this->getCheckoutUrl(); ?>");
        },
        onClick: function() { alert(1); },
        onError: function(error) {
            console.log(error);
        }
    };

    OffAmazonPayments.Button("<?php echo $this->getAmazonPayButtonId(); ?>", "<?php echo $this->getSellerId(); ?>", AmazonButtonOptions);

    // Focus popup window on click (e.g. if already open and hidden behind main window)
    var timeoutShowPopup; // Prevent blank tab from opening if already signed in
    $("<?php echo $this->getAmazonPayButtonId(); ?>").observe("click", function() { timeoutShowPopup = setTimeout(function() { window.open('', 'amazonloginpopup', '').focus(); }, 500); })
    Event.observe(window, "beforeunload", function() { clearTimeout(timeoutShowPopup); });

  </script>

<?php endif; ?>