<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<div id="popup-header">
    <img src="<?php echo $this->getSkinUrl('amazon_payments/logo.png', array('_secure'=>true)); ?>" id="amazon-payments-logo">
</div>