<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>


<div id="popup-footer">
    <ul id="popup-footer-links">
        <li><a href="https://payments.amazon.com/help/Personal-Accounts/User-Agreement-Policies/User-Agreement" target="_blank"><?php print $this->__('Terms of Service'); ?></a></li>
        <li><a href="https://payments.amazon.com/help/Personal-Accounts/Privacy-Security/Privacy-Notice" target="_blank"><?php print $this->__('Privacy Notice'); ?></a></li>
        <li><a href="https://payments.amazon.com/contact" target="_blank"><?php print $this->__('Share Feedback'); ?></a></li>
    </ul>
    <div id="popup-footer-right">
        &copy; 1996-<?php echo date('Y');?>, Amazon.com, Inc. or its affiliates
        <br />
        <a href="#" onclick="parent.Windows.close('amazon_modal', event)"><?php print $this->__('Cancel and return to %s', Mage::app()->getStore()->getName()); ?></a>

    </div>
</div>