<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php
    $_helper = Mage::helper('amazon_payments/data');
?>

<script type='text/javascript'>
  window.onAmazonLoginReady = function() {
    amazon.Login.setClientId('<?php echo $_helper->getClientId(); ?>');
  };
</script>

<?php $sandbox = ($_helper->isAmazonSandbox()) ? 'sandbox/' : ''; ?>

<script type='text/javascript' src='https://static-na.payments-amazon.com/OffAmazonPayments/us/<?php echo $sandbox; ?>js/Widgets.js?sellerId=<?php echo $_helper->getSellerId(); ?>'></script>


<?php if ($_helper->showModal()) : ?>

<script type="text/javascript">

AmazonModal = Class.create();

AmazonModal.prototype.initialize = function(width) {
    this.width = width;
}

AmazonModal.prototype.show = function(url) {

    this.oPopup = new Window({
        id:'amazon_modal',
        className: 'alphacube',
        url: url,
        width: this.width,
        height: 700,
        minimizable: false,
        maximizable: false,
        showEffectOptions: {
            duration: 0.4
        },
        hideEffectOptions:{
            duration: 0.4
        },
        destroyOnClose: true,
        onShow: function() { Event.observe($('overlay_modal'), 'click', function() { Windows.closeAll(); }) }
    });
    this.oPopup.setZIndex(100);
    this.oPopup.showCenter(true);

    // Reponsive modal
    Event.observe(window, "resize", this.resize.bind(this));
    this.resize();
}

AmazonModal.prototype.resize = function() {
    var oSize = this.oPopup.getSize();
    var width = document.viewport.getWidth();

    if (this.width > width) {
      this.oPopup.setSize(width, oSize.height);
    }
}




document.observe("dom:loaded", function() {
    var amazonModal = new AmazonModal(1020);
    amazonModal.show('<?php print $_helper->getStandaloneUrl(); ?>?ajax=1&<?php print $_SERVER['QUERY_STRING']; ?>');
});


</script>

<?php endif; ?>