<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php
    $_helper = Mage::helper('amazon_payments/data');
?>

<script type='text/javascript'>
  window.onAmazonLoginReady = function() {
    amazon.Login.setClientId('<?php echo $_helper->getClientId(); ?>');
  };

</script>

<?php $sandbox = ($_helper->isAmazonSandbox()) ? 'sandbox/' : ''; ?>

<script type='text/javascript' src='https://static-na.payments-amazon.com/OffAmazonPayments/us/<?php echo $sandbox; ?>js/Widgets.js?sellerId=<?php echo $_helper->getSellerId(); ?>'></script>
