<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<h2><?php echo $this->__('Shipping Method'); ?></h2>

<form id="co-shipping-method-form" action="">
    <div id="checkout-shipping-method-load">
       <!-- Content loaded dynamically -->
    </div>

    <div id="checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>

</form>
