<?php
/**
 * Login with Amazon
 *
 * @category    Amazon
 * @package     Amazon_Login
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>


<?php

/**
 * More button styles: http://login.amazon.com/button-guide
 */

$login_button = <<<END

  <div class="amazon-login-button-wrapper">
      <strong>- {$this->__('OR')} -</strong>
      <br />

      <button class="amazon-login-button" style="cursor:pointer; background:none; border:0;">
        <img src="http://g-ecx.images-amazon.com/images/G/01/lwa/btnLWA_gold_156x32.png"
          width="156" height="32" alt="Login with Amazon" border="0" />
      </button>
  </div>

END;

?>

<div id="amazon-buttons-wrapper" class="col2-set">
    <div class="col-1">
        <?php echo $login_button; ?>
    </div>
    <div class="col-2">
        <?php echo $login_button; ?>
    </div>
</div>