<?php
/**
 * Login with Amazon
 *
 * @category    Amazon
 * @package     Amazon_Login
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php
/**
 * @see https://images-na.ssl-images-amazon.com/images/G/01/lwa/dev/docs/website-sdk-reference._TTH_.pdf
 */
?>

<div id="amazon-root"></div>
<script type="text/javascript">

window.onAmazonLoginReady = function() {
    <?php if ($this->isSandboxEnabled()) : ?>
    amazon.Login.setSandboxMode(true);
    <?php endif; ?>
    amazon.Login.setClientId('<?php echo $this->getClientId(); ?>');
};
(function(d) {
    var a = d.createElement('script'); a.type = 'text/javascript';
    a.async = true; a.id = 'amazon-login-sdk';
    a.src = 'https://api-cdn.amazon.com/sdk/login1.js';
    d.getElementById('amazon-root').appendChild(a);
})(document);



function amazonLoginAuthorize() {
    options = { scope : 'profile postal_code payments:shipping_address<?php print $this->getAdditionalScope(); ?>', response_type: 'token', popup: <?php print $this->getIsPopup(); ?> };

    <?php if ($this->isPopup()) : ?>

      var responseRedirect = function(response) {
        if (response.error) {
            console.log(response.error);
        }
        else {
          document.location.href = "<?php echo $this->getUrl('amazon_login/customer/authorize', array('_forced_secure' => true))?>?token=" + response.access_token + "&referer=<?php echo Mage::helper('core')->urlEncode($this->helper('core/url')->getCurrentUrl())?>";
        }
      }

    <?php else: ?>

        var responseRedirect = "<?php echo $this->getUrl('amazon_login/customer/authorize', array('_forced_secure' => true))?>";

    <?php endif; ?>

    amazon.Login.authorize(options, responseRedirect);
}

$$('.amazon-login-button').each(function(el) {
    el.observe('click', amazonLoginAuthorize);
})

</script>

<?php if ($this->getNameInLayout() == 'amazon_login.script.logout') : ?>

<script type="text/javascript">

window.onAmazonLoginReady = function() {
    amazon.Login.logout();
};

</script>

<?php endif; ?>