<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>


<!--<h3><?php echo $this->__('Pay with Amazon'); ?></h3>-->


<div id="<?php echo $this->getAmazonPayButtonId(); ?>"></div>
<script type="text/javascript">
  var authRequest;

  var AmazonButtonOptions = {
      type: "LwA",
      authorization: function() {
          loginOptions = {
              scope: "profile payments:widget payments:shipping_address"
          };

          authRequest = amazon.Login.authorize (loginOptions, "<?php echo $this->getOnepageCheckoutUrl(); ?>");
      },
      onError: function(error) {
          console.log(error);
      }
  };

  OffAmazonPayments.Button("<?php echo $this->getAmazonPayButtonId(); ?>", "<?php echo $this->getSellerId(); ?>", AmazonButtonOptions);
</script>


<br />
<p><strong>- <?php echo $this->__('OR'); ?> -</strong></p>
<br />